In [67]:
import numpy as np
import random

In [68]:
def normalize(arr, arr_max, arr_min):
    ran = arr_max - arr_min
    arr_nor = []
    for n in range(len(arr)):
         arr_nor.append((arr[n] - arr_min) / arr_max)
    return arr_nor

In [69]:
arr = []
for n in np.arange(25):
    arr.append(random.randint(0, 10))
arr_max = np.max(arr)
arr_min = np.min(arr)
arr_nor = normalize(arr, arr_max, arr_min)
arr_reshape = np.reshape(arr_nor,(5,5))
print(arr)
print('----------------------------------------------------------')
print(arr_reshape)

[10, 1, 4, 8, 7, 7, 9, 5, 7, 8, 3, 3, 0, 5, 8, 0, 6, 4, 4, 7, 9, 2, 0, 10, 10]
----------------------------------------------------------
[[1.  0.1 0.4 0.8 0.7]
 [0.7 0.9 0.5 0.7 0.8]
 [0.3 0.3 0.  0.5 0.8]
 [0.  0.6 0.4 0.4 0.7]
 [0.9 0.2 0.  1.  1. ]]


In [70]:
arr2 = np.arange(10)
ind = np.where(arr2 == np.max(arr2))
arr2[ind] = -1
print(arr2)

[ 0  1  2  3  4  5  6  7  8 -1]


In [75]:
array1 = np.arange(30)
array1_reshape = np.reshape(array1,(5,6))
np.where(array1 % 6 == 1)

(array([ 1,  7, 13, 19, 25], dtype=int64),)