In [1]:
import numpy as np

In [2]:
arr1 = [i for i in range(0,21,1)]
print(arr1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [10]:
arr1 = np.array(arr1)
print(arr1)
print(type(arr1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>


In [11]:
arr2 = arr1[0:len(arr1):2]
print(arr2)
print(type(arr2))

[ 0  2  4  6  8 10 12 14 16 18 20]
<class 'numpy.ndarray'>


In [12]:
arr3 = arr1[0:len(arr1):3]
print(arr3)
print(type(arr2))

[ 0  3  6  9 12 15 18]
<class 'numpy.ndarray'>
