In [1]:
import numpy as np
import random

In [31]:
arr = []
for i in range(21):
    arr.append(random.randint(1,5))
arr1 = arr[0:6]; arr2 = arr[6:]
# print(arr); print(arr1); print(arr2)
arr1_reshape = np.reshape(arr1,(2,3))
arr2_reshape = np.reshape(arr2,(3,5))
print(arr1_reshape); print(arr2_reshape)
arr_mul = arr1_reshape.dot(arr2_reshape)
print(arr_mul)

[[3 4 1]
 [2 2 4]]
[[1 4 4 5 2]
 [2 1 4 3 4]
 [5 1 2 3 2]]
[[16 17 30 30 24]
 [26 14 24 28 20]]


In [40]:
array1 = np.array([[10, 8], [3, 5]])
e, v = np.linalg.eig(array1)
print(e); print(v)
y = v * np.diag(e) * np.linalg.inv(v)
print(y)

[13.  2.]
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]
[[ 9.45454545 -1.09845872]
 [-1.76054344  1.45454545]]
