In [2]:
import numpy as np

In [7]:
arr1 = np.array(range(0,30))
print(arr1)
print(type(arr1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
<class 'numpy.ndarray'>


In [35]:
arr2 = np.reshape(arr1,(5,6), order = 'C')
print(arr2)
print(type(arr2))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
<class 'numpy.ndarray'>


In [36]:
arr3 = np.where(arr2 % 6 == 1)
print(arr3)

(array([0, 1, 2, 3, 4], dtype=int64), array([1, 1, 1, 1, 1], dtype=int64))
